### ISSUE TITLE
CAYENNE_STRNCMP vs strncmp not consistent

### ISSUE THREAD

**Issue by MaJerle** [myDevicesIoT/Cayenne-MQTT-C#8]
Hello Cayenne team,

not really an issue, but more advice. Make code consistent all the time. Currently, you use `strncmp` standard C function, while somewhere you use `CAYENNE_STRNCMP` which is actually `strncmp`.

https://github.com/myDevicesIoT/Cayenne-MQTT-C/blob/a33610a1bda23e4b71ae1b0e46af376b03cd6fa1/src/CayenneUtils/CayenneUtils.c#L432

or 

https://github.com/myDevicesIoT/Cayenne-MQTT-C/blob/a33610a1bda23e4b71ae1b0e46af376b03cd6fa1/src/CayenneUtils/CayenneUtils.c#L429

**Comment by jburhenn** [comment]
The reason for the discrepancy is this code is used as the basis for the Cayenne-MQTT-Arduino library which uses PROGMEM string functions for things like `THINGS_STRING`. So it needs to use the `strncmp_P` version of the function for those comparisons. `CAYENNE_STRNCMP` is set to `strncmp_P` when compiled for Arduino. But things like `index` are stored in SRAM so they require the standard `strncmp` function for comparison. So we need to use both in different situations.
