### ISSUE TITLE
visual studio

### ISSUE THREAD

**Issue by kalai86** [myDevicesIoT/Cayenne-MQTT-C#9]
hi,

 i am using visual studio 2015 .i got error like  the windows sdk version 10.0.1.16299.0 was not found  the required version of windows sdk or change the sdk version in the project properties.

error 2;
 
 the build tools for v141 cannot be found ..to build using the v141 build tools 

thanks
kv

**Comment by jburhenn** [comment]
Those sound like Visual Studio errors, not errors with this library. You might try a Visual Studio forum for help fixing those issues. You could also try the Cayenne community forums in case anyone else has run into those problems before: https://community.mydevices.com/.
